import { Battery, MapPin, PanelTop, PlugZap } from "lucide-react";
import { INDIA_SITES } from "@/lib/india";
import { BATTERY_PRESETS, batteryBank, type SimulationConfig } from "@/lib/simulator";
import type { ReactNode } from "react";

export function NumericField({ label, value, onChange, min = 0, max = 100000, step = 1, unit, hint }: { label: string; value: number; onChange: (value: number) => void; min?: number; max?: number; step?: number; unit?: string; hint?: string }) {
  return <label className="block space-y-1.5 text-xs"><span className="text-muted-foreground">{label}</span><div className="relative"><input type="number" inputMode="decimal" aria-label={label} min={min} max={max} step={step} value={value} onChange={(e) => { const next = Number(e.target.value); if (Number.isFinite(next)) onChange(Math.min(max, Math.max(min, step === 1 ? Math.round(next) : next))); }} className="numeric h-10 w-full rounded-lg border border-border bg-background px-3 pr-10 text-sm font-medium outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20" /><span className="pointer-events-none absolute right-3 top-3 text-[10px] text-muted-foreground">{unit}</span></div>{hint && <span className="block text-[10px] leading-relaxed text-muted-foreground">{hint}</span>}</label>;
}
export function Choice({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: ReactNode }) {
  return <label className="block space-y-1.5 text-xs"><span className="text-muted-foreground">{label}</span><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary/30">{children}</select></label>;
}
function Block({ number, title, icon, children }: { number: string; title: string; icon: ReactNode; children: ReactNode }) {
  return <section className="panel-surface p-5"><div className="mb-5 flex items-center gap-2.5"><span className="numeric text-[10px] text-primary">{number}</span><h3 className="flex-1 text-sm font-semibold">{title}</h3><span className="text-muted-foreground">{icon}</span></div><div className="space-y-4">{children}</div></section>;
}
export function Equipment({ config, onChange }: { config: SimulationConfig; onChange: (config: SimulationConfig) => void }) {
  const s = config.solar, b = config.battery, i = config.inverter, bank = batteryBank(config);
  const solar = (patch: Partial<typeof s>) => onChange({ ...config, solar: { ...s, ...patch } });
  const battery = (patch: Partial<typeof b>) => onChange({ ...config, battery: { ...b, ...patch } });
  const inverter = (patch: Partial<typeof i>) => onChange({ ...config, inverter: { ...i, ...patch } });
  const siteId = INDIA_SITES.find((site) => site.latitude === config.location.latitude && site.longitude === config.location.longitude)?.id ?? "custom";
  const batteryEnabled = config.grid.mode !== "grid-tied";
  return <div className="space-y-4">
    <Block number="01" title="Place & operating mode" icon={<MapPin className="size-4" />}>
      <Choice label="Indian location · all times in IST" value={siteId} onChange={(id) => { const site = INDIA_SITES.find((p) => p.id === id); if (site) onChange({ ...config, location: { name: site.name, latitude: site.latitude, longitude: site.longitude } }); }}>{INDIA_SITES.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}<option value="custom">Custom coordinates</option></Choice>
      <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Custom coordinates</summary><div className="mt-3 grid grid-cols-2 gap-3"><NumericField label="Latitude" value={config.location.latitude} min={6} max={38} step={0.01} unit="°N" onChange={(latitude) => onChange({ ...config, location: { ...config.location, name: "Custom India site", latitude } })} /><NumericField label="Longitude" value={config.location.longitude} min={68} max={98} step={0.01} unit="°E" onChange={(longitude) => onChange({ ...config, location: { ...config.location, name: "Custom India site", longitude } })} /></div></details>
      <Choice label="How your home is connected" value={config.grid.mode} onChange={(mode) => onChange({ ...config, grid: { ...config.grid, mode: mode as typeof config.grid.mode } })}><option value="off-grid">Off-grid · solar + battery only</option><option value="hybrid">Hybrid · mains bypass + solar backup</option><option value="grid-tied">On-grid · no backup during cuts</option></Choice>
      <p className="text-[11px] leading-relaxed text-muted-foreground">230 V / 50 Hz AC context. Hybrid uses mains bypass while available; no grid charging or export credit is assumed.</p>
      <div className="grid grid-cols-2 gap-3"><NumericField label="Simulation length" value={config.days} min={1} max={7} unit="days" onChange={(days) => onChange({ ...config, days })} /><NumericField label="Start day of year" value={config.startDay} min={1} max={365} unit="day" onChange={(startDay) => onChange({ ...config, startDay })} /></div>
      {config.grid.mode !== "off-grid" && <div className="space-y-3 border-t border-border pt-3"><NumericField label="Energy tariff (variable charge only)" value={config.grid.tariff} max={50} step={0.1} unit="₹/kWh" onChange={(tariff) => onChange({ ...config, grid: { ...config.grid, tariff } })} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={config.grid.outages.length > 0} onChange={(e) => onChange({ ...config, grid: { ...config.grid, outages: e.target.checked ? [{ start: 1080, duration: 120 }] : [] } })} />Daily mains power cut</label>{config.grid.outages.map((cut, index) => <div className="grid grid-cols-2 gap-3" key={index}><NumericField label={`Cut ${index + 1} starts (minutes after midnight)`} value={cut.start} max={1439} unit="min" onChange={(start) => onChange({ ...config, grid: { ...config.grid, outages: config.grid.outages.map((w, j) => j === index ? { ...w, start } : w) } })} /><NumericField label={`Cut ${index + 1} duration`} value={cut.duration} min={1} max={1440} unit="min" onChange={(duration) => onChange({ ...config, grid: { ...config.grid, outages: config.grid.outages.map((w, j) => j === index ? { ...w, duration } : w) } })} /></div>)}</div>}
    </Block>
    <Block number="02" title="Your solar array" icon={<PanelTop className="size-4" />}>
      <div className="grid grid-cols-2 gap-3"><NumericField label="Number of panels" value={s.count} max={1000} onChange={(count) => solar({ count })} /><NumericField label="Each panel's nameplate" value={s.watts} min={1} max={2000} unit="W" onChange={(watts) => solar({ watts })} /></div>
      <div className="rounded-lg bg-primary/10 px-3 py-2 text-xs"><strong className="numeric">{(s.count * s.watts / 1000).toFixed(2)} kWp</strong><span className="text-muted-foreground"> installed DC · not constant output</span></div>
      <div className="grid grid-cols-2 gap-3"><NumericField label="Module tilt" value={s.tilt} max={70} unit="°" onChange={(tilt) => solar({ tilt })} /><NumericField label="Facing (180° = south)" value={s.azimuth} max={360} unit="°" onChange={(azimuth) => solar({ azimuth })} /></div>
      {batteryEnabled && <NumericField label="Solar charge controller limit" value={s.controllerAmps} max={1000} unit="A" onChange={(controllerAmps) => solar({ controllerAmps })} hint={`DC input is capped at nominal ${bank.volts} V × controller A. Verify the actual MPPT/PWM specification.`} />}
      <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Solar assumptions · editable, not weather data</summary><div className="mt-3 space-y-3"><NumericField label="Clearness assumption" value={s.clearness} min={0} max={1} step={0.05} onChange={(clearness) => solar({ clearness })} hint="0 = overcast heuristic; 1 = clear. Constant for this run, not a monsoon forecast." /><NumericField label="Ambient temperature" value={s.temperature} min={-10} max={55} unit="°C" onChange={(temperature) => solar({ temperature })} /><NumericField label="DC losses" value={s.losses * 100} max={80} unit="%" step={0.1} onChange={(losses) => solar({ losses: losses / 100 })} /></div></details>
    </Block>
    <Block number="03" title="Battery bank" icon={<Battery className="size-4" />}>
      {!batteryEnabled ? <p className="text-xs text-muted-foreground">On-grid mode has no battery backup. Choose hybrid or off-grid to configure storage.</p> : <>
        <Choice label="Battery chemistry" value={b.chemistry} onChange={(chemistry) => { const preset = BATTERY_PRESETS[chemistry as keyof typeof BATTERY_PRESETS]; battery({ chemistry: chemistry as typeof b.chemistry, reserveSoc: preset.reserveSoc, chargeEfficiency: preset.chargeEfficiency, dischargeEfficiency: preset.dischargeEfficiency, ratedHours: preset.ratedHours, peukertExponent: preset.peukertExponent }); }}>{Object.entries(BATTERY_PRESETS).map(([key, preset]) => <option key={key} value={key}>{preset.label}</option>)}</Choice>
        <div className="grid grid-cols-2 gap-3"><NumericField label="Each battery voltage" value={b.unitVolts} min={2} max={60} step={0.1} unit="V" onChange={(unitVolts) => battery({ unitVolts })} /><NumericField label="Each battery capacity" value={b.unitAh} min={1} max={3000} unit="Ah" onChange={(unitAh) => battery({ unitAh })} /><NumericField label="Batteries in series" value={b.series} min={1} max={16} onChange={(series) => battery({ series })} /><NumericField label="Parallel strings" value={b.parallel} min={1} max={16} onChange={(parallel) => battery({ parallel })} /></div>
        <div className="rounded-lg border border-border bg-muted/50 p-3"><p className="numeric text-sm font-semibold">{bank.volts} V · {bank.ah} Ah · {(bank.wh / 1000).toFixed(2)} kWh</p><p className="mt-1 text-[11px] text-muted-foreground">{bank.units} batteries · {(bank.usableWh / 1000).toFixed(2)} kWh above reserve before conversion losses. Series raises V; parallel raises Ah.</p></div>
        <div className="grid grid-cols-2 gap-3"><NumericField label="Starting charge" value={b.initialSoc} max={100} unit="%" onChange={(initialSoc) => battery({ initialSoc })} /><NumericField label="Minimum reserve" value={b.reserveSoc} max={95} unit="%" onChange={(reserveSoc) => battery({ reserveSoc })} /><NumericField label="Max bank charge current" value={b.chargeAmps} max={1000} unit="A" onChange={(chargeAmps) => battery({ chargeAmps })} /><NumericField label="Max bank discharge current" value={b.dischargeAmps} max={1000} unit="A" onChange={(dischargeAmps) => battery({ dischargeAmps })} /></div>
        <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Battery efficiencies & discharge-rate effect</summary><div className="mt-3 grid grid-cols-2 gap-3"><NumericField label="Charge efficiency" value={b.chargeEfficiency * 100} min={50} max={100} unit="%" step={0.1} onChange={(value) => battery({ chargeEfficiency: value / 100 })} /><NumericField label="Discharge efficiency" value={b.dischargeEfficiency * 100} min={50} max={100} unit="%" step={0.1} onChange={(value) => battery({ dischargeEfficiency: value / 100 })} /><NumericField label="Ah rating period (e.g. C20)" value={b.ratedHours ?? 20} min={1} max={100} unit="h" onChange={(ratedHours) => battery({ ratedHours })} /><NumericField label="Peukert exponent (1 = disabled)" value={b.peukertExponent ?? 1} min={1} max={1.5} step={0.01} onChange={(peukertExponent) => battery({ peukertExponent })} /></div><p className="mt-2 text-[10px] leading-relaxed text-muted-foreground">Approximate high-current capacity penalty for lead-acid; use manufacturer data. Lithium typically uses 1. No extra capacity credit at low currents.</p></details>
      </>}
    </Block>
    <Block number="04" title="Inverter / solar UPS" icon={<PlugZap className="size-4" />}>
      <div className="grid grid-cols-2 gap-3"><NumericField label="Continuous rating" value={i.va} min={1} max={100000} unit="VA" onChange={(va) => inverter({ va })} /><NumericField label="Rated W / VA factor" value={i.ratedPowerFactor} min={0.2} max={1} step={0.05} onChange={(ratedPowerFactor) => inverter({ ratedPowerFactor })} /></div>
      <p className="numeric rounded-lg bg-muted/50 p-3 text-xs">Usable continuous ceiling: {(i.va * i.ratedPowerFactor).toFixed(0)} W · read both W and VA on the datasheet.</p>
      <div className="grid grid-cols-2 gap-3"><NumericField label="Startup surge ceiling" value={i.surgeWatts} min={1} max={200000} unit="W" onChange={(surgeWatts) => inverter({ surgeWatts })} /><NumericField label="Required DC bank voltage" value={i.dcVolts} min={2} max={1000} step={0.1} unit="V" onChange={(dcVolts) => inverter({ dcVolts })} /><NumericField label="DC → AC efficiency" value={i.efficiency * 100} min={50} max={100} unit="%" step={0.1} onChange={(value) => inverter({ efficiency: value / 100 })} /><NumericField label="Idle consumption (DC)" value={i.idleWatts} max={500} unit="W" onChange={(idleWatts) => inverter({ idleWatts })} /></div>
      <p className="text-[11px] leading-relaxed text-muted-foreground">Surge check is an admission estimate, not a motor-start transient model. All AC loads are on one assumed backup circuit. No grid-bypass current limit is modeled. Verify waveform, surge duration, wiring and compatibility with an installer.</p>
    </Block>
  </div>;
}
