import { Battery, ChevronDown, MapPin, Minus, PanelTop, PlugZap, Plus } from "lucide-react";
import { INDIA_SITES } from "@/lib/india";
import { BATTERY_PRESETS, batteryBank, type SimulationConfig } from "@/lib/simulator";
import type { ReactNode } from "react";

export function NumericField({ label, value, onChange, min = 0, max = 100000, step = 1, unit, hint, slider = false, sliderMin, sliderMax }: { label: string; value: number; onChange: (value: number) => void; min?: number; max?: number; step?: number; unit?: string; hint?: string; slider?: boolean; sliderMin?: number; sliderMax?: number }) {
  const clamp = (next: number) => onChange(Math.min(max, Math.max(min, step === 1 ? Math.round(next) : Math.round(next / step) * step)));
  return <div className="block space-y-1.5 text-xs"><span className="text-muted-foreground">{label}</span><div className="flex gap-1.5"><button type="button" aria-label={`Decrease ${label}`} onClick={() => clamp(value - step)} className="grid size-10 shrink-0 place-items-center rounded-lg border border-border bg-card text-muted-foreground transition-colors hover:bg-muted hover:text-foreground active:scale-95"><Minus className="size-3.5" /></button><div className="relative min-w-0 flex-1"><input type="number" inputMode="decimal" aria-label={label} min={min} max={max} step={step} value={value} onChange={(e) => { const next = Number(e.target.value); if (Number.isFinite(next)) clamp(next); }} className="numeric h-10 w-full rounded-lg border border-border bg-background px-2.5 pr-9 text-center text-sm font-semibold outline-none focus-visible:border-primary focus-visible:ring-2 focus-visible:ring-primary/20" /><span className="pointer-events-none absolute right-2.5 top-3 text-[10px] text-muted-foreground">{unit}</span></div><button type="button" aria-label={`Increase ${label}`} onClick={() => clamp(value + step)} className="grid size-10 shrink-0 place-items-center rounded-lg border border-border bg-card text-muted-foreground transition-colors hover:bg-muted hover:text-foreground active:scale-95"><Plus className="size-3.5" /></button></div>{slider && (sliderMax ?? max) > (sliderMin ?? min) && <input type="range" aria-label={`${label} slider`} min={sliderMin ?? min} max={sliderMax ?? max} step={step} value={Math.min(sliderMax ?? max, Math.max(sliderMin ?? min, value))} onChange={(e) => clamp(Number(e.target.value))} className="w-full" />}{hint && <span className="block text-[10px] leading-relaxed text-muted-foreground">{hint}</span>}</div>;
}
export function Choice({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: ReactNode }) {
  return <label className="block space-y-1.5 text-xs"><span className="text-muted-foreground">{label}</span><select aria-label={label} value={value} onChange={(e) => onChange(e.target.value)} className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary/30">{children}</select></label>;
}
export function Segmented<T extends string>({ label, value, onChange, options }: { label: string; value: T; onChange: (value: T) => void; options: { value: T; title: string; hint?: string }[] }) {
  return <div role="radiogroup" aria-label={label} className="space-y-1.5 text-xs"><span className="text-muted-foreground">{label}</span><div className="grid gap-1.5">{options.map((opt) => { const active = opt.value === value; return <button key={opt.value} type="button" role="radio" aria-checked={active} onClick={() => onChange(opt.value)} className={`flex items-center gap-3 rounded-xl border px-3 py-2.5 text-left transition-all active:scale-[0.99] ${active ? "border-primary/50 bg-primary/[0.07] shadow-[0_6px_18px_-10px_oklch(0.585_0.16_44/0.5)]" : "border-border bg-card hover:border-muted-foreground/40"}`}><span className={`grid size-4 shrink-0 place-items-center rounded-full border-2 ${active ? "border-primary" : "border-muted-foreground/40"}`}>{active && <span className="size-1.5 rounded-full bg-primary" />}</span><span className="min-w-0"><span className="block text-[0.8rem] font-semibold leading-tight">{opt.title}</span>{opt.hint && <span className="mt-0.5 block text-[10px] leading-snug text-muted-foreground">{opt.hint}</span>}</span></button>; })}</div></div>;
}
function Block({ number, title, icon, summary, children, defaultOpen = true }: { number: string; title: string; icon: ReactNode; summary?: string; children: ReactNode; defaultOpen?: boolean }) {
  return <section className="panel-surface relative overflow-hidden"><span className="absolute inset-x-0 top-0 h-0.5 bg-gradient-to-r from-amber-400/60 via-primary/50 to-transparent" /><details open={defaultOpen} className="group p-5"><summary className="flex cursor-pointer list-none items-center gap-2.5 select-none [&::-webkit-details-marker]:hidden"><span className="numeric rounded-md bg-primary/10 px-1.5 py-0.5 text-[10px] font-semibold text-primary">{number}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{title}</span>{summary && <span className="numeric mt-0.5 block truncate text-[11px] text-muted-foreground">{summary}</span>}</span><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground">{icon}</span><ChevronDown className="size-4 shrink-0 text-muted-foreground transition-transform group-open:rotate-180" /></summary><div className="space-y-4 pt-5">{children}</div></details></section>;
}
export function Equipment({ config, onChange }: { config: SimulationConfig; onChange: (config: SimulationConfig) => void }) {
  const s = config.solar, b = config.battery, i = config.inverter, bank = batteryBank(config);
  const solar = (patch: Partial<typeof s>) => onChange({ ...config, solar: { ...s, ...patch } });
  const battery = (patch: Partial<typeof b>) => onChange({ ...config, battery: { ...b, ...patch } });
  const inverter = (patch: Partial<typeof i>) => onChange({ ...config, inverter: { ...i, ...patch } });
  const siteId = INDIA_SITES.find((site) => site.latitude === config.location.latitude && site.longitude === config.location.longitude)?.id ?? "custom";
  const batteryEnabled = config.grid.mode !== "grid-tied";
  return <div className="space-y-4">
    <Block number="01" title="Place & operating mode" icon={<MapPin className="size-4" />} summary={`${config.location.name} · ${config.grid.mode === "off-grid" ? "Off-grid" : config.grid.mode === "hybrid" ? "Hybrid bypass" : "On-grid"} · ${config.days}d`}>
      <Choice label="Indian location · all times in IST" value={siteId} onChange={(id) => { const site = INDIA_SITES.find((p) => p.id === id); if (site) onChange({ ...config, location: { name: site.name, latitude: site.latitude, longitude: site.longitude } }); }}>{INDIA_SITES.map((site) => <option key={site.id} value={site.id}>{site.name}</option>)}<option value="custom">Custom coordinates</option></Choice>
      <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Custom coordinates</summary><div className="mt-3 grid grid-cols-2 gap-3"><NumericField label="Latitude" value={config.location.latitude} min={6} max={38} step={0.01} unit="°N" onChange={(latitude) => onChange({ ...config, location: { ...config.location, name: "Custom India site", latitude } })} /><NumericField label="Longitude" value={config.location.longitude} min={68} max={98} step={0.01} unit="°E" onChange={(longitude) => onChange({ ...config, location: { ...config.location, name: "Custom India site", longitude } })} /></div></details>
      <Segmented label="How your home is connected" value={config.grid.mode} onChange={(mode) => onChange({ ...config, grid: { ...config.grid, mode } })} options={[{ value: "off-grid", title: "Off-grid", hint: "Solar + battery only · 230 V / 50 Hz" }, { value: "hybrid", title: "Hybrid", hint: "Mains bypass when available · no grid charging, no export" }, { value: "grid-tied", title: "On-grid", hint: "No backup during cuts · battery hidden" }]} />
      <div className="grid grid-cols-2 gap-3"><NumericField label="Simulation length" value={config.days} min={1} max={7} unit="days" onChange={(days) => onChange({ ...config, days })} /><NumericField label="Start day of year" value={config.startDay} min={1} max={365} unit="day" onChange={(startDay) => onChange({ ...config, startDay })} /></div>
      {config.grid.mode !== "off-grid" && <div className="space-y-3 border-t border-border pt-3"><NumericField label="Energy tariff (variable charge only)" value={config.grid.tariff} max={50} step={0.1} unit="₹/kWh" onChange={(tariff) => onChange({ ...config, grid: { ...config.grid, tariff } })} /><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={config.grid.outages.length > 0} onChange={(e) => onChange({ ...config, grid: { ...config.grid, outages: e.target.checked ? [{ start: 1080, duration: 120 }] : [] } })} />Daily mains power cut</label>{config.grid.outages.map((cut, index) => <div className="grid grid-cols-2 gap-3" key={index}><NumericField label={`Cut ${index + 1} starts (minutes after midnight)`} value={cut.start} max={1439} unit="min" onChange={(start) => onChange({ ...config, grid: { ...config.grid, outages: config.grid.outages.map((w, j) => j === index ? { ...w, start } : w) } })} /><NumericField label={`Cut ${index + 1} duration`} value={cut.duration} min={1} max={1440} unit="min" onChange={(duration) => onChange({ ...config, grid: { ...config.grid, outages: config.grid.outages.map((w, j) => j === index ? { ...w, duration } : w) } })} /></div>)}</div>}
    </Block>
    <Block number="02" title="Your solar array" icon={<PanelTop className="size-4" />} summary={`${(s.count * s.watts / 1000).toFixed(2)} kWp · ${s.count} × ${s.watts} W · ${s.tilt}° / ${s.azimuth}°`}>
      <div className="grid grid-cols-2 gap-3"><NumericField slider sliderMin={1} sliderMax={12} label="Number of panels" value={s.count} min={1} max={1000} onChange={(count) => solar({ count })} /><NumericField slider label="Each panel's nameplate" value={s.watts} min={50} max={800} step={5} unit="W" onChange={(watts) => solar({ watts })} /></div>
      <div className="rounded-lg bg-primary/10 px-3 py-2 text-xs"><strong className="numeric">{(s.count * s.watts / 1000).toFixed(2)} kWp</strong><span className="text-muted-foreground"> installed DC · not constant output</span></div>
      <div className="grid grid-cols-2 gap-3"><NumericField slider label="Module tilt" value={s.tilt} max={70} unit="°" onChange={(tilt) => solar({ tilt })} /><NumericField slider label="Facing (180° = south)" value={s.azimuth} max={360} step={5} unit="°" onChange={(azimuth) => solar({ azimuth })} /></div>
      {batteryEnabled && <NumericField label="Solar charge controller limit" value={s.controllerAmps} max={1000} unit="A" onChange={(controllerAmps) => solar({ controllerAmps })} hint={`DC input is capped at nominal ${bank.volts} V × controller A. Verify the actual MPPT/PWM specification.`} />}
      <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Solar assumptions · editable, not weather data</summary><div className="mt-3 space-y-3"><NumericField label="Clearness assumption" value={s.clearness} min={0} max={1} step={0.05} onChange={(clearness) => solar({ clearness })} hint="0 = overcast heuristic; 1 = clear. Constant for this run, not a monsoon forecast." /><NumericField label="Ambient temperature" value={s.temperature} min={-10} max={55} unit="°C" onChange={(temperature) => solar({ temperature })} /><NumericField label="DC losses" value={s.losses * 100} max={80} unit="%" step={0.1} onChange={(losses) => solar({ losses: losses / 100 })} /></div></details>
    </Block>
    <Block number="03" title="Battery bank" icon={<Battery className="size-4" />} summary={batteryEnabled ? `${bank.volts} V · ${bank.ah} Ah · ${(bank.wh / 1000).toFixed(2)} kWh (${(bank.usableWh / 1000).toFixed(2)} usable)` : "No storage in on-grid mode"} defaultOpen={batteryEnabled}>
      {!batteryEnabled ? <p className="text-xs text-muted-foreground">On-grid mode has no battery backup. Choose hybrid or off-grid to configure storage.</p> : <>
        <Choice label="Battery chemistry" value={b.chemistry} onChange={(chemistry) => { const preset = BATTERY_PRESETS[chemistry as keyof typeof BATTERY_PRESETS]; battery({ chemistry: chemistry as typeof b.chemistry, reserveSoc: preset.reserveSoc, chargeEfficiency: preset.chargeEfficiency, dischargeEfficiency: preset.dischargeEfficiency, ratedHours: preset.ratedHours, peukertExponent: preset.peukertExponent }); }}>{Object.entries(BATTERY_PRESETS).map(([key, preset]) => <option key={key} value={key}>{preset.label}</option>)}</Choice>
        <div className="grid grid-cols-2 gap-3"><NumericField label="Each battery voltage" value={b.unitVolts} min={2} max={60} step={0.1} unit="V" onChange={(unitVolts) => battery({ unitVolts })} /><NumericField slider label="Each battery capacity" value={b.unitAh} min={20} max={500} step={5} unit="Ah" onChange={(unitAh) => battery({ unitAh })} /><NumericField slider label="Batteries in series" value={b.series} min={1} max={16} onChange={(series) => battery({ series })} /><NumericField slider label="Parallel strings" value={b.parallel} min={1} max={16} onChange={(parallel) => battery({ parallel })} /></div>
        <div className="rounded-lg border border-border bg-muted/50 p-3"><p className="numeric text-sm font-semibold">{bank.volts} V · {bank.ah} Ah · {(bank.wh / 1000).toFixed(2)} kWh</p><p className="mt-1 text-[11px] text-muted-foreground">{bank.units} batteries · {(bank.usableWh / 1000).toFixed(2)} kWh above reserve before conversion losses. Series raises V; parallel raises Ah.</p></div>
        <div className="grid grid-cols-2 gap-3"><NumericField label="Starting charge" value={b.initialSoc} max={100} unit="%" onChange={(initialSoc) => battery({ initialSoc })} /><NumericField label="Minimum reserve" value={b.reserveSoc} max={95} unit="%" onChange={(reserveSoc) => battery({ reserveSoc })} /><NumericField label="Max bank charge current" value={b.chargeAmps} max={1000} unit="A" onChange={(chargeAmps) => battery({ chargeAmps })} /><NumericField label="Max bank discharge current" value={b.dischargeAmps} max={1000} unit="A" onChange={(dischargeAmps) => battery({ dischargeAmps })} /></div>
        <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Battery efficiencies & discharge-rate effect</summary><div className="mt-3 grid grid-cols-2 gap-3"><NumericField label="Charge efficiency" value={b.chargeEfficiency * 100} min={50} max={100} unit="%" step={0.1} onChange={(value) => battery({ chargeEfficiency: value / 100 })} /><NumericField label="Discharge efficiency" value={b.dischargeEfficiency * 100} min={50} max={100} unit="%" step={0.1} onChange={(value) => battery({ dischargeEfficiency: value / 100 })} /><NumericField label="Ah rating period (e.g. C20)" value={b.ratedHours ?? 20} min={1} max={100} unit="h" onChange={(ratedHours) => battery({ ratedHours })} /><NumericField label="Peukert exponent (1 = disabled)" value={b.peukertExponent ?? 1} min={1} max={1.5} step={0.01} onChange={(peukertExponent) => battery({ peukertExponent })} /></div><p className="mt-2 text-[10px] leading-relaxed text-muted-foreground">Approximate high-current capacity penalty for lead-acid; use manufacturer data. Lithium typically uses 1. No extra capacity credit at low currents.</p></details>
      </>}
    </Block>
    <Block number="04" title="Inverter / solar UPS" icon={<PlugZap className="size-4" />} summary={`${i.va} VA · ${(i.va * i.ratedPowerFactor).toFixed(0)} W usable · surge ${i.surgeWatts} W${Math.abs(bank.volts - i.dcVolts) > 0.01 && batteryEnabled ? " · ⚠ bank/inverter V differ" : ""}`}>
      {batteryEnabled && Math.abs(bank.volts - i.dcVolts) > 0.01 && <p role="alert" className="rounded-xl border border-destructive/25 bg-destructive/[0.06] px-3 py-2 text-[11px] leading-relaxed">Bank is {bank.volts} V but the inverter expects {i.dcVolts} V — loads will report a voltage mismatch. Fix series count or inverter DC volts.</p>}
      <div className="grid grid-cols-2 gap-3"><NumericField slider label="Continuous rating" value={i.va} min={200} max={10000} step={50} unit="VA" onChange={(va) => inverter({ va })} /><NumericField label="Rated W / VA factor" value={i.ratedPowerFactor} min={0.2} max={1} step={0.05} onChange={(ratedPowerFactor) => inverter({ ratedPowerFactor })} /></div>
      <p className="numeric rounded-lg bg-muted/50 p-3 text-xs">Usable continuous ceiling: {(i.va * i.ratedPowerFactor).toFixed(0)} W · read both W and VA on the datasheet.</p>
      <div className="grid grid-cols-2 gap-3"><NumericField label="Startup surge ceiling" value={i.surgeWatts} min={1} max={200000} unit="W" onChange={(surgeWatts) => inverter({ surgeWatts })} /><NumericField label="Required DC bank voltage" value={i.dcVolts} min={2} max={1000} step={0.1} unit="V" onChange={(dcVolts) => inverter({ dcVolts })} /><NumericField label="DC → AC efficiency" value={i.efficiency * 100} min={50} max={100} unit="%" step={0.1} onChange={(value) => inverter({ efficiency: value / 100 })} /><NumericField label="Idle consumption (DC)" value={i.idleWatts} max={500} unit="W" onChange={(idleWatts) => inverter({ idleWatts })} /></div>
      <p className="text-[11px] leading-relaxed text-muted-foreground">Surge check is an admission estimate, not a motor-start transient model. All AC loads are on one assumed backup circuit. No grid-bypass current limit is modeled. Verify waveform, surge duration, wiring and compatibility with an installer.</p>
    </Block>
  </div>;
}
