import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { INDIA_LOAD_PRESETS, makeLoad, scheduledDailyMinutes, type ScheduledLoad } from "@/lib/simulator";
import { formatMinutes } from "@/lib/solar";
import { Choice, NumericField } from "./Equipment";
import { useState } from "react";

function timeValue(minute: number) { return formatMinutes(minute); }
function DayBar({ windows, enabled }: { windows: { start: number; duration: number }[]; enabled: boolean }) {
  const blocks: { left: number; width: number }[] = [];
  for (const w of windows) {
    const end = w.start + w.duration;
    if (end <= 1440) blocks.push({ left: w.start / 1440 * 100, width: Math.max(0.8, w.duration / 1440 * 100) });
    else { blocks.push({ left: w.start / 1440 * 100, width: (1440 - w.start) / 1440 * 100 }); blocks.push({ left: 0, width: (end - 1440) / 1440 * 100 }); }
  }
  return <div className="relative h-2.5 overflow-hidden rounded-full bg-muted" role="img" aria-label="Daily run windows on a 24-hour bar">{[6, 12, 18].map((h) => <span key={h} className="absolute top-0 h-full w-px bg-border" style={{ left: `${h / 24 * 100}%` }} />)}{blocks.map((b, i) => <span key={i} className={`absolute top-0 h-full rounded-full ${enabled ? "bg-primary" : "bg-muted-foreground/40"}`} style={{ left: `${b.left}%`, width: `${b.width}%` }} />)}</div>;
}
const QUICK: { label: string; start: number; duration: number }[] = [{ label: "Morning", start: 360, duration: 120 }, { label: "Midday", start: 720, duration: 120 }, { label: "Evening", start: 1080, duration: 180 }, { label: "Night", start: 1320, duration: 240 }];
export function Schedule({ loads, onChange }: { loads: ScheduledLoad[]; onChange: (loads: ScheduledLoad[]) => void }) {
  const [preset, setPreset] = useState("0");
  const update = (id: string, patch: Partial<ScheduledLoad>) => onChange(loads.map((load) => load.id === id ? { ...load, ...patch } : load));
  const add = (custom = false) => {
    const load = makeLoad(Number(preset), crypto.randomUUID());
    onChange([...loads, custom ? { ...load, name: "Custom appliance", watts: 100, surgeMultiplier: 1, powerFactor: 1 } : load]);
  };
  return <section className="panel-surface p-4 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow text-primary">The household</p><h2 className="display mt-1 text-[1.45rem] font-semibold">When does everything run?</h2><p className="mt-1 max-w-xl text-xs leading-relaxed text-muted-foreground">Schedules repeat daily in IST. Midnight-crossing runs are supported. Priority 1 is served first; ties follow list order.</p></div><span className="numeric rounded-full bg-muted px-3 py-1 text-xs">{loads.filter((load) => load.enabled).length} active loads</span></div>
    <div className="mt-5 flex flex-wrap items-end gap-2"><div className="min-w-0 flex-1"><Choice label="Add a common Indian household appliance" value={preset} onChange={setPreset}>{INDIA_LOAD_PRESETS.map((p, index) => <option key={p.name} value={index}>{p.name} · {p.watts} W</option>)}</Choice></div><Button onClick={() => add()} disabled={loads.length >= 50}><Plus className="size-4" />Add</Button><Button variant="outline" onClick={() => add(true)} disabled={loads.length >= 50}>Custom</Button></div>
    <div className="mt-5 space-y-3">{loads.length === 0 && <div className="rounded-xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Add your first appliance to see demand, battery use and shortfalls.</div>}{loads.map((load, index) => <article key={load.id} className={`rounded-xl border border-border p-4 ${load.enabled ? "bg-background/60" : "opacity-60"}`}>
      <div className="flex items-center gap-3"><span className="numeric text-[10px] text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><input type="checkbox" aria-label={`Enable ${load.name}`} checked={load.enabled} onChange={(e) => update(load.id, { enabled: e.target.checked })} className="size-4 accent-[var(--color-primary)]" /><input aria-label={`Appliance ${index + 1} name`} value={load.name} maxLength={100} onChange={(e) => update(load.id, { name: e.target.value || "Appliance" })} className="min-w-0 flex-1 rounded-md border border-transparent bg-transparent px-1 py-1 text-sm font-semibold outline-none focus-visible:border-primary" /><span className="numeric hidden text-[10px] text-muted-foreground sm:inline">{load.enabled ? `${(load.watts * load.quantity)} W` : "off"}</span><Button size="icon" variant="ghost" aria-label={`Remove ${load.name}`} onClick={() => onChange(loads.filter((item) => item.id !== load.id))}><Trash2 className="size-4" /></Button></div>
      <div className="mt-2.5"><DayBar windows={load.windows} enabled={load.enabled} /><div className="mt-1.5 flex flex-wrap items-center gap-1.5">{QUICK.map((q) => <button key={q.label} type="button" onClick={() => update(load.id, { windows: [{ start: q.start, duration: q.duration }] })} className="rounded-full border border-border px-2 py-0.5 text-[10px] font-medium text-muted-foreground transition-colors hover:border-primary/50 hover:text-foreground" title={`Set to ${q.label} run`}>{q.label}</button>)}<span className="ml-auto text-[10px] text-muted-foreground">{(load.watts * load.quantity * scheduledDailyMinutes(load) / 60000).toFixed(2)} kWh/day</span></div></div>
      <div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"><NumericField label="Running watts / unit" value={load.watts} min={1} max={30000} unit="W" onChange={(watts) => update(load.id, { watts })} /><NumericField label="Quantity" value={load.quantity} min={1} max={50} onChange={(quantity) => update(load.id, { quantity })} /><NumericField label="Priority (1 = first)" value={load.priority} min={1} max={10} onChange={(priority) => update(load.id, { priority })} /><div className="flex flex-col justify-center rounded-lg bg-muted/60 px-3"><span className="text-[10px] text-muted-foreground">Scheduled energy / day</span><strong className="numeric mt-1 text-sm">{(load.watts * load.quantity * scheduledDailyMinutes(load) / 60000).toFixed(2)} kWh</strong></div></div>
      <div className="mt-4 space-y-2">{load.windows.map((window, windowIndex) => <div key={windowIndex} className="flex flex-wrap items-end gap-3"><label className="block flex-1 space-y-1.5 text-xs"><span className="text-muted-foreground">Start · IST</span><input type="time" aria-label={`${load.name} schedule ${windowIndex + 1} start`} value={timeValue(window.start)} onChange={(e) => { const [hour, minute] = e.target.value.split(":").map(Number); if (Number.isFinite(hour) && Number.isFinite(minute)) update(load.id, { windows: load.windows.map((w, j) => j === windowIndex ? { ...w, start: hour * 60 + minute } : w) }); }} className="numeric h-10 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-primary/20" /></label><div className="min-w-24 flex-1"><NumericField label="Duration" value={window.duration} min={1} max={1440} unit="min" onChange={(duration) => update(load.id, { windows: load.windows.map((w, j) => j === windowIndex ? { ...w, duration } : w) })} /></div><p className="pb-3 text-[11px] text-muted-foreground">until {formatMinutes(window.start + window.duration)}{window.start + window.duration >= 1440 ? " +1 day" : ""}</p>{load.windows.length > 1 && <Button size="icon" variant="ghost" aria-label={`Remove schedule ${windowIndex + 1} for ${load.name}`} onClick={() => update(load.id, { windows: load.windows.filter((_, j) => j !== windowIndex) })}><Trash2 className="size-3.5" /></Button>}</div>)}</div>
      <details className="mt-3 text-xs"><summary className="cursor-pointer text-muted-foreground">Startup, duty cycling & additional schedules</summary><div className="mt-3 grid grid-cols-2 gap-3"><NumericField label="Startup watts multiplier" value={load.surgeMultiplier} min={1} max={10} step={0.1} unit="×" onChange={(surgeMultiplier) => update(load.id, { surgeMultiplier })} /><NumericField label="Appliance power factor" value={load.powerFactor} min={0.2} max={1} step={0.05} onChange={(powerFactor) => update(load.id, { powerFactor })} /></div><label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" checked={!!load.cycle} onChange={(e) => update(load.id, { cycle: e.target.checked ? { period: 60, on: 20 } : undefined })} />Repeat an on/off cycle inside each schedule</label>{load.cycle && <div className="mt-3 grid grid-cols-2 gap-3"><NumericField label="Cycle period" value={load.cycle.period} min={1} max={1440} unit="min" onChange={(period) => update(load.id, { cycle: { period, on: Math.min(period, load.cycle!.on) } })} /><NumericField label="On-time per cycle" value={load.cycle.on} min={1} max={load.cycle.period} unit="min" onChange={(on) => update(load.id, { cycle: { ...load.cycle!, on } })} /></div>}<Button variant="outline" size="sm" className="mt-3" disabled={load.windows.length >= 8} onClick={() => update(load.id, { windows: [...load.windows, { start: 480, duration: 60 }] })}><Plus className="size-3" />Another run</Button></details>
    </article>)}</div>
    <p className="mt-4 text-[11px] leading-relaxed text-muted-foreground">Overlapping windows count once. Presets are assumptions, not certified ratings. The fridge preset uses 20 minutes on per 60-minute cycle; edit it to match measured behavior. Duty cycling is deterministic, not a thermostat or compressor-temperature model. Use running watts with cycles, or average watts without cycles—not both discounts.</p>
  </section>;
}
