import { Plus, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { INDIA_LOAD_PRESETS, makeLoad, scheduledDailyMinutes, type ScheduledLoad } from "@/lib/simulator";
import { formatMinutes } from "@/lib/solar";
import { Choice, NumericField } from "./Equipment";
import { useState } from "react";

function timeValue(minute: number) { return formatMinutes(minute); }
function DayBar({ windows, enabled }: { windows: { start: number; duration: number }[]; enabled: boolean }) {
  const blocks: { left: number; width: number }[] = [];
  for (const w of windows) {
    const end = w.start + w.duration;
    if (end <= 1440) blocks.push({ left: w.start / 1440 * 100, width: Math.max(0.8, w.duration / 1440 * 100) });
    else { blocks.push({ left: w.start / 1440 * 100, width: (1440 - w.start) / 1440 * 100 }); blocks.push({ left: 0, width: (end - 1440) / 1440 * 100 }); }
  }
  return <div className="relative h-2.5 overflow-hidden rounded-full bg-muted" role="img" aria-label="Usage window across 24 hours">{[6, 12, 18].map((h) => <span key={h} className="absolute top-0 h-full w-px bg-border" style={{ left: `${h / 24 * 100}%` }} />)}{blocks.map((b, i) => <span key={i} className={`absolute top-0 h-full rounded-full transition-colors duration-200 ${enabled ? "bg-primary" : "bg-muted-foreground/40"}`} style={{ left: `${b.left}%`, width: `${b.width}%` }} />)}</div>;
}
const QUICK: { label: string; start: number; duration: number }[] = [{ label: "Morning", start: 360, duration: 120 }, { label: "Midday", start: 720, duration: 120 }, { label: "Evening", start: 1080, duration: 180 }, { label: "Night", start: 1320, duration: 240 }];
export function Schedule({ loads, onChange }: { loads: ScheduledLoad[]; onChange: (loads: ScheduledLoad[]) => void }) {
  const [preset, setPreset] = useState("1");
  const update = (id: string, patch: Partial<ScheduledLoad>) => onChange(loads.map((load) => load.id === id ? { ...load, ...patch } : load));
  const add = (custom = false) => {
    const load = makeLoad(Number(preset), crypto.randomUUID());
    onChange([...loads, custom ? { ...load, name: "Custom load", watts: 100, surgeMultiplier: 1, powerFactor: 1 } : load]);
  };
  return <section className="panel-surface rounded-[1.4rem] px-6 py-6 sm:px-7">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-primary">Appliances & schedule</p><h2 className="display mt-2 text-[1.45rem] font-semibold tracking-tight">What runs, and when</h2><p className="mt-2 max-w-xl text-[13px] leading-relaxed text-muted-foreground">Add appliances and set daily running hours. The schedule repeats each day of the study.</p></div><span className="numeric rounded-full border border-border/70 bg-muted/50 px-3.5 py-1.5 text-xs font-semibold">{loads.filter((load) => load.enabled).length} active</span></div>
    <div className="mt-6 flex flex-wrap items-end gap-2.5"><div className="min-w-0 flex-1 basis-52"><Choice label="Appliance preset" value={preset} onChange={setPreset}>{INDIA_LOAD_PRESETS.map((p, index) => <option key={p.name} value={index}>{p.name} · {p.watts} W</option>)}</Choice></div><Button onClick={() => add()} disabled={loads.length >= 50} className="h-12 rounded-2xl px-5"><Plus className="size-4" />Add</Button><Button variant="outline" onClick={() => add(true)} disabled={loads.length >= 50} className="h-12 rounded-2xl px-4">Custom</Button></div>
    <div className="mt-6 space-y-5">{loads.length === 0 && <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">No appliances yet. Add a fan or light to see results.</div>}{loads.map((load, index) => <article key={load.id} className={`rounded-[1.2rem] border p-6 transition-all duration-200 ${load.enabled ? "border-border/80 bg-background/60 shadow-[0_1px_2px_oklch(0.3_0.05_58/0.05)]" : "border-border/60 opacity-60"}`}>
      <div className="flex items-center gap-3"><span className="numeric text-[11px] font-medium text-muted-foreground">{String(index + 1).padStart(2, "0")}</span><input type="checkbox" aria-label={`Enable ${load.name}`} checked={load.enabled} onChange={(e) => update(load.id, { enabled: e.target.checked })} className="size-[18px] accent-[var(--color-primary)]" /><input aria-label={`Appliance ${index + 1} name`} value={load.name} maxLength={100} onChange={(e) => update(load.id, { name: e.target.value || "Appliance" })} className="min-w-0 flex-1 rounded-lg border border-transparent bg-transparent px-2 py-1.5 text-[15px] font-semibold tracking-tight outline-none transition-colors focus-visible:border-primary focus-visible:bg-card" /><span className="numeric hidden rounded-full bg-muted/60 px-2.5 py-1 text-xs font-medium text-muted-foreground sm:inline">{load.enabled ? `${(load.watts * load.quantity)} W` : "Off"}</span><Button size="icon" variant="ghost" aria-label={`Remove ${load.name}`} onClick={() => onChange(loads.filter((item) => item.id !== load.id))} className="rounded-xl"><Trash2 className="size-4" /></Button></div>
      <div className="mt-5"><DayBar windows={load.windows} enabled={load.enabled} /><div className="mt-3 flex flex-wrap items-center gap-1.5">{QUICK.map((q) => <button key={q.label} type="button" onClick={() => update(load.id, { windows: [{ start: q.start, duration: q.duration }] })} className="rounded-full border border-border/80 px-3.5 py-1.5 text-xs font-medium text-muted-foreground transition-all duration-200 hover:border-primary/50 hover:text-foreground hover:shadow-sm">{q.label}</button>)}<span className="numeric ml-auto text-xs font-medium text-muted-foreground">≈ {(load.watts * load.quantity * scheduledDailyMinutes(load) / 60000).toFixed(2)} kWh/day</span></div></div>
      <div className="mt-5 grid gap-6 sm:grid-cols-2"><NumericField label="Rated power" value={load.watts} min={1} max={30000} step={5} sliderMin={5} sliderMax={2000} unit="W" onChange={(watts) => update(load.id, { watts })} /><NumericField label="Quantity" value={load.quantity} min={1} max={50} sliderMin={1} sliderMax={10} onChange={(quantity) => update(load.id, { quantity })} /><div className="col-span-2 flex flex-col justify-center rounded-2xl bg-muted/40 px-5 py-3.5 sm:col-span-2"><span className="text-[11px] font-medium text-muted-foreground">Daily consumption</span><strong className="numeric mt-1 text-base font-semibold">{(load.watts * load.quantity * scheduledDailyMinutes(load) / 60000).toFixed(2)} kWh</strong></div></div>
      <div className="mt-5 space-y-4">{load.windows.map((window, windowIndex) => <div key={windowIndex} className="flex flex-wrap items-end gap-5"><label className="block flex-1 basis-44 text-sm"><span className="text-[13px] font-semibold tracking-tight text-foreground">Start time</span><input type="time" aria-label={`${load.name} start time`} value={timeValue(window.start)} onChange={(e) => { const [hour, minute] = e.target.value.split(":").map(Number); if (Number.isFinite(hour) && Number.isFinite(minute)) update(load.id, { windows: load.windows.map((w, j) => j === windowIndex ? { ...w, start: hour * 60 + minute } : w) }); }} className="numeric mt-2.5 h-12 w-full rounded-2xl border border-border/80 bg-background px-3.5 text-sm font-medium outline-none transition-all duration-200 focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/15" /></label><div className="min-w-28 flex-1 basis-36"><NumericField label="Duration" value={window.duration} min={5} max={1440} step={5} sliderMin={15} sliderMax={720} unit="min" hint={`Runs until ${formatMinutes(window.start + window.duration)}${window.start + window.duration >= 1440 ? " (next day)" : ""}`} onChange={(duration) => update(load.id, { windows: load.windows.map((w, j) => j === windowIndex ? { ...w, duration } : w) })} /></div>{load.windows.length > 1 && <Button size="icon" variant="ghost" aria-label={`Remove timing ${windowIndex + 1}`} onClick={() => update(load.id, { windows: load.windows.filter((_, j) => j !== windowIndex) })}><Trash2 className="size-3.5" /></Button>}</div>)}</div>
      <details className="mt-5 rounded-2xl bg-muted/25 px-5 py-4 text-sm"><summary className="cursor-pointer text-[13px] font-medium text-muted-foreground transition-colors hover:text-foreground">Priority, starting surge & extra timings</summary><div className="mt-5 grid grid-cols-2 gap-5"><NumericField label="Priority" value={load.priority} min={1} max={10} hint="1 is served first during shortage." onChange={(priority) => update(load.id, { priority })} /><NumericField label="Starting surge" value={load.surgeMultiplier} min={1} max={10} step={0.1} unit="×" hint="Motors need 3–4× briefly." onChange={(surgeMultiplier) => update(load.id, { surgeMultiplier })} /></div><label className="mt-5 flex cursor-pointer items-center gap-2.5 text-[13px] font-medium"><input type="checkbox" checked={!!load.cycle} onChange={(e) => update(load.id, { cycle: e.target.checked ? { period: 60, on: 20 } : undefined })} className="size-4 accent-[var(--color-primary)]" />Compressor cycling (fridge, cooler)</label>{load.cycle && <div className="mt-5 grid grid-cols-2 gap-5"><NumericField label="Cycle length" value={load.cycle.period} min={1} max={1440} sliderMin={15} sliderMax={180} unit="min" onChange={(period) => update(load.id, { cycle: { period, on: Math.min(period, load.cycle!.on) } })} /><NumericField label="On-time per cycle" value={load.cycle.on} min={1} max={load.cycle.period} sliderMin={5} sliderMax={120} unit="min" onChange={(on) => update(load.id, { cycle: { ...load.cycle!, on } })} /></div>}<Button variant="outline" size="sm" className="mt-5 h-9 rounded-xl" disabled={load.windows.length >= 8} onClick={() => update(load.id, { windows: [...load.windows, { start: 480, duration: 60 }] })}><Plus className="size-3" />Add another timing</Button></details>
    </article>)}</div>
    <p className="mt-6 text-xs leading-relaxed text-muted-foreground">Preset ratings are typical values — check the appliance nameplate for exact watts. The refrigerator preset includes 20 min/hour compressor cycling.</p>
  </section>;
}
