import { motion } from "framer-motion";
import { ArrowRight, BatteryCharging, BoxSelect, Check, Clock3, Fan, Lightbulb, PanelTop, PlugZap, Sun, Tv, Zap } from "lucide-react";
import { Link } from "react-router";
import { Button } from "@/components/ui/button";
import { defaultSimulation, simulate } from "@/lib/simulator";

const example = defaultSimulation();
const run = simulate({ ...example, days: 1 });
const heroPoints = run.steps.filter((_, index) => index % 12 === 0);
const powerPath = heroPoints.map((s, index) => `${index === 0 ? "M" : "L"}${24 + s.minute / 1440 * 480},${170 - s.solarW / 440 * 140}`).join(" ");
const demandPath = heroPoints.map((s, index) => `${index === 0 ? "M" : "L"}${24 + s.minute / 1440 * 480},${170 - s.demandW / 440 * 140}`).join(" ");

function EnergyPreview() {
  return <div className="relative rounded-3xl border border-border bg-card p-5 shadow-[0_30px_80px_-45px_oklch(0_0_0/0.35)] sm:p-7">
    <div className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-xs font-medium"><span className="size-2 rounded-full bg-primary" />A small system. A real question.</span><span className="rounded-full bg-muted px-2.5 py-1 text-[9px] tracking-wider text-muted-foreground">NEW DELHI · IST</span></div>
    <div className="mt-6 grid grid-cols-3 divide-x divide-border">{[[PanelTop, "2 × 220 W", "Solar panels"], [BatteryCharging, "12 V · 150 Ah", "Tubular battery"], [PlugZap, "900 VA", "Solar inverter"]].map(([Icon, value, label]) => { const Component = Icon as typeof Sun; return <div key={label as string} className="px-2 text-center"><Component className="mx-auto size-5 text-primary" /><p className="numeric mt-3 text-sm font-semibold">{value as string}</p><p className="mt-1 text-[10px] text-muted-foreground">{label as string}</p></div>; })}</div>
    <div className="mt-6 rounded-2xl border border-border bg-muted/20 p-3"><div className="flex justify-between text-[10px] text-muted-foreground"><span>Solar vs household demand</span><span>One modeled day</span></div><svg viewBox="0 0 530 205" className="mt-3 w-full" role="img" aria-label="Example solar rises during daylight while household demand peaks in the evening"><defs><linearGradient id="landing-solar" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#d29932" stopOpacity="0.28" /><stop offset="100%" stopColor="#d29932" stopOpacity="0.02" /></linearGradient></defs>{[50, 110, 170].map((y) => <line key={y} x1="24" y1={y} x2="504" y2={y} stroke="var(--color-border)" strokeDasharray="3 5" />)}<path d={`${powerPath} L504,170 L24,170 Z`} fill="url(#landing-solar)" /><path d={powerPath} fill="none" stroke="#d29932" strokeWidth="2.5" /><path d={demandPath} fill="none" stroke="#344b61" strokeWidth="2" strokeDasharray="5 3" />{[0, 6, 12, 18, 24].map((h) => <text key={h} x={24 + h / 24 * 480} y="198" textAnchor="middle" fontSize="10" fill="var(--color-muted-foreground)">{String(h).padStart(2, "0")}:00</text>)}</svg><div className="flex gap-4 text-[10px] text-muted-foreground"><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-primary" />Estimated solar DC</span><span className="flex items-center gap-1.5"><span className="size-1.5 rounded-full bg-slate-600" />Scheduled demand AC</span></div></div>
    <div className="mt-5 flex items-center justify-between rounded-xl border border-border p-3"><div className="flex -space-x-1">{[Fan, Lightbulb, Tv, Zap].map((Icon, index) => <span key={index} className="grid size-8 place-items-center rounded-full border-2 border-card bg-muted text-muted-foreground"><Icon className="size-3.5" /></span>)}</div><div className="text-right"><p className="text-xs font-medium">Fans, lights, TV & Wi-Fi</p><p className="mt-1 text-[10px] text-muted-foreground">Not all energy is available when you need it.</p></div></div>
    <p className="mt-4 text-[10px] leading-relaxed text-muted-foreground">Actual engine output for the example setup, not a weather forecast. Edit every rating, schedule and solar assumption in the simulator.</p>
  </div>;
}
export default function Landing() {
  return <div className="min-h-screen bg-background text-foreground">
    <header className="border-b border-border/70"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between gap-3 px-5 sm:px-8"><Link to="/" className="flex items-center gap-2 text-xl font-semibold tracking-tight"><span className="grid size-9 place-items-center rounded-xl bg-primary/15 text-primary"><Sun className="size-5" /></span>helio<span className="ml-2 hidden text-[10px] font-medium tracking-[0.16em] text-muted-foreground sm:inline">ENERGY LAB</span></Link><div className="flex items-center gap-2"><Link to="/auth" className="px-3 text-xs text-muted-foreground hover:text-foreground">Sign in</Link><Button asChild size="sm"><Link to="/auth?returnTo=%2Fsimulator">Open simulator <ArrowRight className="size-3.5" /></Link></Button></div></div></header>
    <section className="relative mx-auto grid max-w-7xl items-center gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1fr_1fr] lg:gap-16"><div><motion.p initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3 py-1.5 text-[10px] font-medium tracking-[0.1em] text-primary uppercase"><span className="size-1.5 rounded-full bg-primary" />Built around Indian homes</motion.p><motion.h1 initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mt-6 text-5xl font-semibold leading-[1.05] tracking-[-0.045em] sm:text-6xl lg:text-7xl">Less guesswork.<br />More <span className="text-primary">sun-powered</span><br />everyday life.</motion.h1><p className="mt-6 max-w-lg text-base leading-relaxed text-muted-foreground">Two panels or a whole rooftop. Find out what your solar, battery and inverter can power—together, through the day, and through a power cut.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild size="lg" className="h-12 px-6"><Link to="/auth?returnTo=%2Fsimulator">Test my solar system <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="outline" className="h-12 px-6"><Link to="/auth?returnTo=%2Fdashboard"><BoxSelect className="size-4" />Plan my roof</Link></Button></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-xs text-muted-foreground">{["Custom panels & Ah batteries", "IST appliance schedules", "No roof drawing required"].map((text) => <span key={text} className="flex items-center gap-1.5"><Check className="size-3 text-primary" />{text}</span>)}</div></div><motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.12 }}><EnergyPreview /></motion.div></section>
    <div className="border-y border-border bg-card/50"><div className="mx-auto grid max-w-7xl grid-cols-2 gap-5 px-5 py-7 sm:grid-cols-4 sm:px-8">{[["V × Ah", "Know your battery’s actual energy"], ["W ≠ VA", "Respect your inverter’s limits"], ["1–7 days", "Carry charge beyond one sunset"], ["230 V / 50 Hz", "Indian household context"]].map(([value, label]) => <div key={value}><p className="numeric text-lg font-semibold tracking-tight">{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{label}</p></div>)}</div></div>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-semibold tracking-[0.16em] text-primary uppercase">TWO TOOLS, ONE BETTER DECISION</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Start with the system. Or the roof.</h2></div><p className="max-w-sm text-sm leading-relaxed text-muted-foreground">Explore your equipment independently, then connect a spatial plan when you’re ready.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><Link to="/auth?returnTo=%2Fsimulator" className="group panel-surface p-7 transition-colors hover:border-primary/40 sm:p-9"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary"><BatteryCharging className="size-6" /></span><span className="text-[10px] tracking-widest text-muted-foreground">01 / USAGE SIMULATOR</span></div><h3 className="mt-7 text-2xl font-semibold tracking-tight">Can it run your everyday?</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Enter panel count and watts, battery chemistry and Ah, series/parallel connections, and inverter VA. Schedule appliances and inspect charge, grid dependence and unmet loads.</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-semibold">Simulate your system <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link><Link to="/auth?returnTo=%2Fdashboard" className="group panel-surface p-7 transition-colors hover:border-primary/40 sm:p-9"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-muted text-foreground"><BoxSelect className="size-6" /></span><span className="text-[10px] tracking-widest text-muted-foreground">02 / 3D ROOF PLANNER</span></div><h3 className="mt-7 text-2xl font-semibold tracking-tight">Where will your panels fit?</h3><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Trace a roof, explore mounting and orientation, and inspect sampled shadows. Send an Indian-site array into the usage simulator while keeping its roof snapshot.</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-semibold">Explore the planner <ArrowRight className="size-4 transition-transform group-hover:translate-x-1" /></span></Link></div></section>
    <section className="border-y border-border bg-muted/40"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-[10px] font-semibold tracking-widest text-primary uppercase">NOT JUST A DAILY TOTAL</p><h2 className="mt-3 text-3xl font-semibold leading-tight tracking-tight">Enough energy is not<br />the same as enough power.</h2><p className="mt-5 text-sm leading-relaxed text-muted-foreground">A pump starting at dinner can change everything. A 150 Ah battery means something different at 12 V and 24 V. Helio makes those assumptions visible.</p></div><div className="space-y-5">{[[PanelTop, "Configure the equipment you actually own", "Use custom nameplate ratings. See nominal bank energy, usable reserve and the separate limits of solar input, battery current and inverter output."], [Clock3, "Put appliances on the same clock", "Fans, lights, a TV, fridge or pump share a daily schedule. Power cuts, overlaps and midnight-crossing runs are modeled in IST."], [Zap, "Compare a change—not a sales promise", "Keep a baseline. Test another battery or inverter, or apply a schedule move backed by an alternate simulated run."]].map(([Icon, title, body], index) => { const Component = Icon as typeof Sun; return <div key={title as string} className="flex gap-4 rounded-xl border border-border bg-card p-5"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Component className="size-4" /></span><div><p className="text-[9px] tracking-widest text-muted-foreground">0{index + 1}</p><h3 className="mt-1 text-sm font-semibold">{title as string}</h3><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{body as string}</p></div></div>; })}</div></div></section>
    <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="rounded-3xl border border-primary/20 bg-primary/5 p-8 sm:p-12"><p className="text-[10px] font-semibold tracking-widest text-primary uppercase">A SMALL SYSTEM IS A GOOD PLACE TO START</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Try two 220 W panels and a 150 Ah battery.</h2><p className="mt-4 max-w-2xl text-sm leading-relaxed text-muted-foreground">The simulator opens with a 12 V tubular battery, a 900 VA inverter, BLDC fan, LED lights, TV and router. Change every detail to match your home.</p><Button asChild size="lg" className="mt-6"><Link to="/auth?returnTo=%2Fsimulator">Open the example <ArrowRight className="size-4" /></Link></Button></div><p className="mt-6 max-w-4xl text-xs leading-relaxed text-muted-foreground">Transparent planning estimates, not certified electrical engineering. Solar curves use editable illustrative assumptions—not measured local weather or a forecast. Lead-acid rate effects and appliance duty cycles use simplified assumptions; battery ageing and real motor-start transients are not modeled. Always confirm equipment, wiring, protection and installation with a qualified professional.</p></section>
    <footer className="border-t border-border"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4 px-5 py-7 text-xs text-muted-foreground sm:px-8"><span className="font-semibold text-foreground">helio / energy lab</span><span>Plan with the sun. Verify on site.</span><Link to="/auth?returnTo=%2Fsimulator" className="hover:text-foreground">Open your workspace →</Link></div></footer>
  </div>;
}
